name: Mantle Data Updater
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 15 * * *'

jobs:
  updateStats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare        
        uses: actions/setup-node@v3
        with:
            node-version: 16
      - run: npm i      
      - name: Mantle Data
        run: node swap-data > mantle.json              
        env:
          EXPORT_MODE: CS
      - uses: EndBug/add-and-commit@v9 
        with: 
          author_name: "Mantle Data Updater"
          add: 'mantle.json --force'
          message: "Mantle Data fetching"
